### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by 2food** [BeepBoopHQ/in-or-out#19]
I don't know what the problem is, but i only get a "channel_not_found" error when i try to use it.

**Comment by Tom5om** [comment]
I get the same

**Comment by selfcontained** [comment]
Are you by chance calling the slash command `/inorout` from inside a private channel the bot isn't invited to?

**Comment by Tom5om** [comment]
Tried multiple channels, didn't get it to work kept getting that error

**Comment by selfcontained** [comment]
I've seen this happen when the bot isn't a member of the channel the slash
command is being called from.

**Comment by 2food** [comment]
Oh, not adding the bot was the problem for me. I didn't know you had to add the bot. Maybe that should be explained better in the tutorial/explanation.
